language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
env: TEST_SUITE=test-main
matrix:
  include:
  - python: "3.6"
    env: TEST_SUITE=lint
install:
  - pip install pycodestyle==2.3.1
  - pip install ./zulip
  - pip install ./zulip_bots
  - pip install ./zulip_botserver
script:
  - tools/$TEST_SUITE
