language: python
sudo: required
python:
  - "3.4"
env:
  matrix:
    - TEST_SUITE=test-main
  global:
    - BOTO_CONFIG=/tmp/nowhere
matrix:
  include:
  - python: "3.4"
    env: TEST_SUITE=backend
    script:
    - wget https://github.com/houstondatavis/slack-export/archive/master.zip
    - mv master.zip slack-export-master.zip
    - zulip/integrations/slack/slackdata2zulipdata.py $PWD/slack-export-master.zip
    - mv zulip_data.tar.gz $HOME
    - cd
    - git clone --depth=50 https://github.com/zulip/zulip.git
    - cd zulip
    - mv ../zulip_data.tar.gz .
    - tar xf zulip_data.tar.gz
    - ls zulip_data
    - ./tools/travis/setup-backend
    - source tools/travis/activate-venv
    - ./manage.py import --destroy-rebuild-database $PWD/zulip_data
    addons:
      postgresql: "9.3"
install:
  - tools/provision
  - source zulip-api-py*-venv/bin/activate
after_success:
  - pip install codecov
  - codecov
